### PR TITLE
Upgrade to SBT 0.13.

### PR DESCRIPTION
**Pull request by petejohanson**
* Core SBT version upgrade.
* Upgrade the various SBT plugins to account for update.

Interested?

### CODE REVIEW

**Comment by taylorleese** [comment]
@petejohanson Hi Pete. Scalamachine isn't actively maintained anymore and the StackMob/PayPal folks are not using it.

**Comment by petejohanson** [comment]
Any active forks/maintainers? Or should I go at it on my own?

**Comment by taylorleese** [comment]
@petejohanson None that I'm aware of.

**Comment by petejohanson** [comment]
So the next question: is StackMob/PayPal likely to have any attachment to the 'scalamachine' name or assert any trademark rights....

**Comment by taylorleese** [comment]
@petejohanson I can't answer that question with any authority unfortunately.

**Comment by petejohanson** [comment]
@taylorleese understood. If I end up doing any significant work, I will probably fork with a new name to be safe.

**Pull request closed without merging**
